security:
  encoders:
    App\Entity\User:
      algorithm: auto
    App\Document\User:
      algorithm: auto

  providers:
    app_user_provider:
      id: App\Security\UserProvider
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: lazy
      stateless: true
      guard:
        authenticators:
          - App\Security\BaseAuthenticator
  access_control:
    -
      path: ^/api
      roles: 'ROLE_AUTHENTICATED'
      allow_if: "request.getPathInfo() !='/api/login' or request.getPathInfo() != '/api/register'"
